/* eslint-disable n8n-nodes-base/node-param-display-name-not-first-position */
/* eslint-disable n8n-nodes-base/node-param-type-options-missing-from-limit */

import type { CoreClawEndpointSpec, CoreClawParamSpec } from '../types';

const offsetParam = (): CoreClawParamSpec => ({
	name: 'offset',
	displayName: 'Offset',
	location: 'query',
	type: 'number',
	default: 0,
	description: 'Result offset. Must be 0 or greater.',
});

const limitParam = (): CoreClawParamSpec => ({
	name: 'limit',
	displayName: 'Limit',
	location: 'query',
	type: 'number',
	default: 50,
	description: 'Max number of results to return',
});

const bodyOffsetParam = (): CoreClawParamSpec => ({ ...offsetParam(), location: 'body' });

const bodyLimitParam = (): CoreClawParamSpec => ({ ...limitParam(), location: 'body' });

const keywordParam = (description: string): CoreClawParamSpec => ({
	name: 'keyword',
	displayName: 'Keyword',
	location: 'query',
	type: 'string',
	default: '',
	description,
});

const workerIdPathParam = (): CoreClawParamSpec => ({
	name: 'workerId',
	displayName: 'Worker ID',
	location: 'path',
	type: 'string',
	default: '',
	required: true,
	description: 'Worker slug or owner path, such as demo-worker or owner~demo-worker',
});

const runIdPathParam = (): CoreClawParamSpec => ({
	name: 'runId',
	displayName: 'Run ID',
	location: 'path',
	type: 'string',
	default: '',
	required: true,
	description: 'Worker run identifier returned by run or list operations',
});

const workerTaskIdPathParam = (): CoreClawParamSpec => ({
	name: 'workerTaskId',
	displayName: 'Worker Task ID',
	location: 'path',
	type: 'string',
	default: '',
	required: true,
	description: 'Saved worker task identifier returned by the list worker tasks operation',
});

const isAsyncParam = (): CoreClawParamSpec => ({
	name: 'is_async',
	displayName: 'Run Asynchronously',
	location: 'body',
	type: 'boolean',
	default: true,
	description: 'Whether CoreClaw should run asynchronously',
});

const callbackUrlParam = (): CoreClawParamSpec => ({
	name: 'callback_url',
	displayName: 'Callback URL',
	location: 'body',
	type: 'string',
	default: '',
	description: 'Optional URL CoreClaw calls with run status updates',
});

const formatParam = (): CoreClawParamSpec => ({
	name: 'format',
	displayName: 'Format',
	location: 'query',
	type: 'string',
	default: 'csv',
	options: [
		{ name: 'CSV', value: 'csv' },
		{ name: 'JSON', value: 'json' },
	],
	description: 'Export file format',
});

const filterKeysParam = (): CoreClawParamSpec => ({
	name: 'filter_keys',
	displayName: 'Filter Keys',
	location: 'query',
	type: 'string',
	default: '',
	description: 'Comma-separated field keys to export. Leave empty to include all fields.',
});

const runBodyParams = (): CoreClawParamSpec[] => [
	callbackUrlParam(),
	isAsyncParam(),
	bodyOffsetParam(),
	bodyLimitParam(),
];

export const excludedEndpointKeys = [
	'POST /api/v2/workers/{workerId}/versions',
	'PUT /api/v2/workers/{workerId}/versions/{version}',
	'GET /api/v2/workers/{workerId}/internal',
] as const;

export const endpointSpecs: CoreClawEndpointSpec[] = [
	{
		resource: 'proxy',
		operation: 'listRegions',
		displayName: 'List Regions',
		action: 'List proxy regions',
		method: 'GET',
		path: '/api/v2/proxy/region',
		auth: false,
		returnsList: true,
		params: [
			{
				name: 'language',
				displayName: 'Language',
				location: 'query',
				type: 'string',
				default: 'en',
				options: [
					{ name: 'English', value: 'en' },
					{ name: 'Chinese', value: 'zh' },
				],
				description: 'Region display language',
			},
		],
	},
	{
		resource: 'storeWorker',
		operation: 'list',
		displayName: 'List',
		action: 'List store workers',
		method: 'GET',
		path: '/api/v2/store',
		auth: false,
		returnsList: true,
		supportsReturnAll: true,
		params: [offsetParam(), limitParam(), keywordParam('Keyword for title, slug, or path.')],
	},
	{
		resource: 'account',
		operation: 'getInfo',
		displayName: 'Get Info',
		action: 'Get account info',
		method: 'GET',
		path: '/api/v2/users/account',
		auth: true,
		params: [],
	},
	{
		resource: 'workerRun',
		operation: 'list',
		displayName: 'List',
		action: 'List worker runs',
		method: 'GET',
		path: '/api/v2/worker-runs',
		auth: true,
		returnsList: true,
		supportsReturnAll: true,
		params: [
			offsetParam(),
			limitParam(),
			{
				name: 'worker_id',
				displayName: 'Worker ID',
				location: 'query',
				type: 'string',
				default: '',
				description: 'Filter by worker slug or owner path',
			},
			{
				name: 'status',
				displayName: 'Status',
				location: 'query',
				type: 'string',
				default: '',
				options: [
					{ name: 'Ready', value: 'ready' },
					{ name: 'Running', value: 'running' },
					{ name: 'Succeeded', value: 'succeeded' },
					{ name: 'Failed', value: 'failed' },
					{ name: 'Aborting', value: 'aborting' },
				],
				description: 'Filter by run status',
			},
		],
	},
	{
		resource: 'workerRun',
		operation: 'getLast',
		displayName: 'Get Last',
		action: 'Get last worker run',
		method: 'GET',
		path: '/api/v2/worker-runs/last',
		auth: true,
		params: [],
	},
	{
		resource: 'workerRun',
		operation: 'abortLast',
		displayName: 'Abort Last',
		action: 'Abort last worker run',
		method: 'POST',
		path: '/api/v2/worker-runs/last/abort',
		auth: true,
		params: runBodyParams(),
	},
	{
		resource: 'workerRun',
		operation: 'exportLastResults',
		displayName: 'Export Last Results',
		action: 'Export last worker run results',
		method: 'GET',
		path: '/api/v2/worker-runs/last/export',
		auth: true,
		params: [formatParam(), filterKeysParam()],
	},
	{
		resource: 'workerRun',
		operation: 'getLastLog',
		displayName: 'Get Last Log',
		action: 'Get last worker run log',
		method: 'GET',
		path: '/api/v2/worker-runs/last/log',
		auth: true,
		params: [],
	},
	{
		resource: 'workerRun',
		operation: 'rerunLast',
		displayName: 'Rerun Last',
		action: 'Rerun last worker run',
		method: 'POST',
		path: '/api/v2/worker-runs/last/rerun',
		auth: true,
		supportsWaitForFinish: true,
		params: runBodyParams(),
	},
	{
		resource: 'workerRun',
		operation: 'listLastResults',
		displayName: 'List Last Results',
		action: 'List last worker run results',
		method: 'GET',
		path: '/api/v2/worker-runs/last/result',
		auth: true,
		returnsList: true,
		supportsReturnAll: true,
		params: [offsetParam(), limitParam()],
	},
	{
		resource: 'workerRun',
		operation: 'get',
		displayName: 'Get',
		action: 'Get worker run',
		method: 'GET',
		path: '/api/v2/worker-runs/{runId}',
		auth: true,
		params: [runIdPathParam()],
	},
	{
		resource: 'workerRun',
		operation: 'abort',
		displayName: 'Abort',
		action: 'Abort worker run',
		method: 'POST',
		path: '/api/v2/worker-runs/{runId}/abort',
		auth: true,
		params: [runIdPathParam()],
	},
	{
		resource: 'workerRun',
		operation: 'getLog',
		displayName: 'Get Log',
		action: 'Get worker run log',
		method: 'GET',
		path: '/api/v2/worker-runs/{runId}/log',
		auth: true,
		params: [runIdPathParam()],
	},
	{
		resource: 'workerRun',
		operation: 'rerun',
		displayName: 'Rerun',
		action: 'Rerun worker run',
		method: 'POST',
		path: '/api/v2/worker-runs/{runId}/rerun',
		auth: true,
		supportsWaitForFinish: true,
		params: [runIdPathParam(), ...runBodyParams()],
	},
	{
		resource: 'workerRun',
		operation: 'listResults',
		displayName: 'List Results',
		action: 'List worker run results',
		method: 'GET',
		path: '/api/v2/worker-runs/{runId}/result',
		auth: true,
		returnsList: true,
		supportsReturnAll: true,
		params: [runIdPathParam(), offsetParam(), limitParam()],
	},
	{
		resource: 'workerRun',
		operation: 'exportResults',
		displayName: 'Export Results',
		action: 'Export worker run results',
		method: 'GET',
		path: '/api/v2/worker-runs/{runId}/result/export',
		auth: true,
		params: [runIdPathParam(), formatParam(), filterKeysParam()],
	},
	{
		resource: 'workerTask',
		operation: 'list',
		displayName: 'List',
		action: 'List worker tasks',
		method: 'GET',
		path: '/api/v2/worker-tasks',
		auth: true,
		returnsList: true,
		supportsReturnAll: true,
		params: [
			offsetParam(),
			limitParam(),
			{
				name: 'worker_id',
				displayName: 'Worker ID',
				location: 'query',
				type: 'string',
				default: '',
				description: 'Filter by worker slug or owner path',
			},
			keywordParam('Keyword for task title or slug.'),
		],
	},
	{
		resource: 'workerTask',
		operation: 'run',
		displayName: 'Run',
		action: 'Run worker task',
		method: 'POST',
		path: '/api/v2/worker-tasks/{workerTaskId}/runs',
		auth: true,
		supportsWaitForFinish: true,
		params: [workerTaskIdPathParam(), ...runBodyParams()],
	},
	{
		resource: 'worker',
		operation: 'list',
		displayName: 'List',
		action: 'List workers',
		method: 'GET',
		path: '/api/v2/workers',
		auth: true,
		returnsList: true,
		supportsReturnAll: true,
		params: [offsetParam(), limitParam(), keywordParam('Keyword for title, slug, or path.')],
	},
	{
		resource: 'worker',
		operation: 'get',
		displayName: 'Get',
		action: 'Get worker',
		method: 'GET',
		path: '/api/v2/workers/{workerId}',
		auth: true,
		params: [workerIdPathParam()],
	},
	{
		resource: 'worker',
		operation: 'getInputSchema',
		displayName: 'Get Input Schema',
		action: 'Get worker input schema',
		method: 'GET',
		path: '/api/v2/workers/{workerId}/input-schema',
		auth: false,
		params: [workerIdPathParam()],
	},
	{
		resource: 'worker',
		operation: 'run',
		displayName: 'Run',
		action: 'Run worker',
		method: 'POST',
		path: '/api/v2/workers/{workerId}/runs',
		auth: true,
		supportsWaitForFinish: true,
		params: [
			workerIdPathParam(),
			{
				name: 'version',
				displayName: 'Version',
				location: 'body',
				type: 'string',
				default: '',
				description: 'Worker script version. Leave empty to use backend default.',
			},
			{
				name: 'input_json',
				displayName: 'Input JSON',
				location: 'body',
				type: 'json',
				default: '',
				description: 'Worker business input JSON. Wrapped as input.parameters.custom.',
			},
			{
				name: 'raw_input_json',
				displayName: 'Raw Input JSON',
				location: 'body',
				type: 'json',
				default: '',
				description: 'Advanced full CoreClaw input object. Do not combine with Input JSON.',
			},
			...runBodyParams(),
		],
	},
	{
		resource: 'worker',
		operation: 'getLastRun',
		displayName: 'Get Last Run',
		action: 'Get worker last run',
		method: 'GET',
		path: '/api/v2/workers/{workerId}/runs/last',
		auth: true,
		params: [workerIdPathParam()],
	},
	{
		resource: 'worker',
		operation: 'abortLastRun',
		displayName: 'Abort Last Run',
		action: 'Abort worker last run',
		method: 'POST',
		path: '/api/v2/workers/{workerId}/runs/last/abort',
		auth: true,
		params: [workerIdPathParam(), ...runBodyParams()],
	},
	{
		resource: 'worker',
		operation: 'exportLastRunResults',
		displayName: 'Export Last Run Results',
		action: 'Export worker last run results',
		method: 'GET',
		path: '/api/v2/workers/{workerId}/runs/last/export',
		auth: true,
		params: [workerIdPathParam(), formatParam(), filterKeysParam()],
	},
	{
		resource: 'worker',
		operation: 'getLastRunLog',
		displayName: 'Get Last Run Log',
		action: 'Get worker last run log',
		method: 'GET',
		path: '/api/v2/workers/{workerId}/runs/last/log',
		auth: true,
		params: [workerIdPathParam()],
	},
	{
		resource: 'worker',
		operation: 'rerunLastRun',
		displayName: 'Rerun Last Run',
		action: 'Rerun worker last run',
		method: 'POST',
		path: '/api/v2/workers/{workerId}/runs/last/rerun',
		auth: true,
		supportsWaitForFinish: true,
		params: [workerIdPathParam(), ...runBodyParams()],
	},
	{
		resource: 'worker',
		operation: 'listLastRunResults',
		displayName: 'List Last Run Results',
		action: 'List worker last run results',
		method: 'GET',
		path: '/api/v2/workers/{workerId}/runs/last/result',
		auth: true,
		returnsList: true,
		supportsReturnAll: true,
		params: [workerIdPathParam(), offsetParam(), limitParam()],
	},
];

export function getEndpointSpec(resource: string, operation: string) {
	return endpointSpecs.find((spec) => spec.resource === resource && spec.operation === operation);
}
